
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
        toolchain: [stable]
        include:
          - os: macos-14
            toolchain: "1.65.0"
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: check typos
        uses: crate-ci/typos@v1.29.4
      - name: Check semver
        continue-on-error: true
        uses: obi1kenobi/cargo-semver-checks-action@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        if: matrix.os == 'macos-14' && matrix.toolchain == 'stable'
        run: cargo clippy --all-targets --workspace
